### ISSUE TITLE
Windows Config

### ISSUE THREAD

**Issue by lopeax** [tylerrrobertson/markup-kombat#1]
Hey there!

Recently found this after having had searched for blade. Was a little annoyed that it didn't have a corresponding windows keymap, but after adding it in, it was pretty fun to use!

Could you add these two lines to the keymap file?

```cson
'atom-text-editor':
  'ctrl-alt-k': 'markup-kombat:konvert'
```

Just for future usage!

**Comment by tylerrrobertson** [comment]
Hey hey!

Hell yes, I can add that! Thanks for the heads up! Glad you're enjoying it.
:) let me know if there's anything else that could be improved on the
Windows side!

-Tyler

On Tuesday, August 18, 2015, lopeax <notifications@github.com> wrote:

> Hey there!
>
> Recently found this after having had searched for blade. Was a little
> annoyed that it didn't have a corresponding windows keymap, but after
> adding it in, it was pretty fun to use!
>
> Could you add these two lines to the keymap file?
>
> 'atom-text-editor':
>   'ctrl-alt-k': 'markup-kombat:konvert'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tylerrrobertson/markup-kombat/issues/1>.
>


-- 
- Tyler Robertson
http://tylerrr.com
@tylerdotdotdot

**Comment by lopeax** [comment]
No problem, one thing that could be done (more of a feature) is changing these to snippets perhaps? If you'd like you can have a look at the snippets repo I've made for the syntax

**Comment by tylerdotdotdot** [comment]
That's a great idea! I honestly just threw this together for fun, but if
people are using it, I'll definitely keep working on perfecting it. I'll
have a look at that repo!

On Tuesday, August 18, 2015, lopeax <notifications@github.com> wrote:

> No problem, one thing that could be done (more of a feature) is changing
> these to snippets perhaps? If you'd like you can have a look at the
> snippets repo I've made for the syntax
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tylerrrobertson/markup-kombat/issues/1#issuecomment-132371895>
> .
>


-- 
- Tyler Robertson
http://tylerrr.com
@tylerdotdotdot
